/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_plugin_gradle.app;

import java_plugin_gradle.list.LinkedList;

import static java_plugin_gradle.utilities.StringUtils.join;
import static java_plugin_gradle.utilities.StringUtils.split;
import static java_plugin_gradle.app.MessageUtils.getMessage;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(result);
    }
}
